packer {
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

variable "aws_access_key" {
  type    = string
  default = ""
}

variable "aws_secret_key" {
  type    = string
  default = ""
}

variable "instance_type" {
  type    = string
  default = ""
}

variable "region" {
  type    = string
  default = ""
}

variable "source_ami" {
  type    = string
  default = ""
}

variable "subnet_id" {
  type    = string
  default = ""
}

variable "vpc_id" {
  type    = string
  default = ""
}

source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.aws_access_key}"
  ami_name      = "DevSecOpsB40-Build-{{timestamp}}"
  instance_type = "${var.instance_type}"
  region        = "${var.region}"
  secret_key    = "${var.aws_secret_key}"
  source_ami    = "${var.source_ami}"
  ssh_username  = "ubuntu"
  subnet_id     = "${var.subnet_id}"
  tags = {
    Name = "DevSecOpsB40-Build-{{timestamp}}"
  }
  vpc_id = "${var.vpc_id}"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30", "sudo apt update -y", "sudo apt install nginx -y", "sudo apt install git -y", "sudo git clone -b DevOpsB31 https://github.com/mavrick202/webhooktesting.git", "sudo rm -rf /var/www/html/index.nginx-debian.html", "sudo cp webhooktesting/index.html /var/www/html/index.nginx-debian.html", "sudo cp webhooktesting/style.css /var/www/html/style.css", "sudo cp webhooktesting/scorekeeper.js /var/www/html/scorekeeper.js", "sudo service nginx start", "sudo systemctl enable nginx", "curl https://get.docker.com | bash"]
  }

  provisioner "file" {
    destination = "/tmp/docker.service"
    source      = "docker.service"
  }

  provisioner "shell" {
    inline = ["sudo cp /tmp/docker.service /lib/systemd/system/docker.service", "sudo usermod -a -G docker ubuntu", "sudo systemctl daemon-reload", "sudo service docker restart"]
  }

}
